name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install meson cmake ninja-build qt6-base-dev qt6-declarative-dev qt6-multimedia-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
      - name: Build application using Meson Build System
        run: |
          meson setup build-meson --buildtype=release
          meson compile -C build-meson
      - name: Build application using CMake
        run: |
          cmake -S . -B build-cmake
          cmake --build build-cmake
      - name: Build application using qmake
        run: |
          mkdir build-qmake
          cd build-qmake
          qmake6 ..
          make
